name: CI Pipeline

on:
  push:
    branches:
      - main  # Trigger pipeline saat ada perubahan di branch main
  pull_request:
    branches:
      - main  # Trigger pipeline saat ada PR ke branch main

jobs:
  build:
    runs-on: ubuntu-latest  # Menjalankan pipeline di lingkungan Ubuntu terbaru

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Checkout kode dari repositori

    - name: Set up Python
      uses: actions/setup-python@v4  # Menyiapkan Python jika proyek menggunakan Python
      with:
        python-version: '3.9'  # Versi Python yang digunakan

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Install dependencies

    - name: Run tests
      run: |
        pytest  # Menjalankan tes
